//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkintegration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FeedbackMaster
    {
        public int UserId { get; set; }
        public int CustId { get; set; }
        public System.DateTime Date { get; set; }

        /*  [Required]
          [Display(Name = "Feedback:")]*/
        public string feedback { get; set; }
    }
}
