//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkintegration.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InsureEntities : DbContext
    {
        public InsureEntities()
            : base("name=InsureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccidentInfo> AccidentInfoes { get; set; }
        public virtual DbSet<FeedbackMaster> FeedbackMasters { get; set; }
        public virtual DbSet<GarrageMaster> GarrageMasters { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<ReportMst> ReportMsts { get; set; }
        public virtual DbSet<Status_surveyor> Status_surveyor { get; set; }
    }
}
