//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace checkintegration.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ReportMst
    {
        public int Id { get; set; }
        public int? SurveyorId { get; set; }
        public string ReportType { get; set; }
        public int AccidentId { get; set; }

        
        [Required(ErrorMessage = "Please select file.")]
        //[RegularExpression(@"([a-zA-Z0-9\s_\\.\-:])+(.doc|.pdf|.xls|.png|.jpg|.gif|.txt)$", ErrorMessage = "Only limited extension files allowed.")]
        public string FilePath { get; set; }
    }
}
